steps:

- id: "Rodando Testes"
  name: 'golang'
  args: ['go', 'test', './...']

- id: "Gerando Imagem"
  name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/golangsum:latest', '.']

- id: "Rodando Imagem"
  name: 'docker'
  args: ['run', '-t', 'gcr.io/$PROJECT_ID/golangsum:latest']

images:
- 'gcr.io/$PROJECT_ID/golangsum:latest'