steps:

- id: "Gerando imagem"
  name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/golangsum:latest', '.']

# - id: "rodando teste unitario"
#   name: 'docker'
#   args: ['exec', '-t', 'app_laravel_code_education', 'php', '/var/www/artisan', 'key:generate']

- id: "rodando imagem"
  name: 'docker'
  args: ['run', '-t', 'gcr.io/$PROJECT_ID/golangsum:latest']