steps:

- id: "Gerando imagem"
  name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/golangsum:latest', '.']

- id: "rodando imagem"
  name: 'docker'
  args: ['run', '-t', 'gcr.io/$PROJECT_ID/golangsum:latest']

- id: "rodando testes"
  name: 'golang'
  args: ['ls -la']